# Generated by Django 4.1.4 on 2023-03-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_student_student_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
